# Generated by Django 4.2.5 on 2023-12-12 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('rut', models.CharField(max_length=50)),
                ('nacimiento', models.DateTimeField()),
                ('edad', models.IntegerField()),
                ('telefono', models.CharField(max_length=15)),
                ('estatura', models.IntegerField()),
                ('peso', models.IntegerField()),
                ('imc', models.DecimalField(decimal_places=2, max_digits=5)),
                ('talla', models.IntegerField()),
                ('cintura', models.IntegerField()),
                ('presion', models.IntegerField()),
                ('f_cardiaca', models.IntegerField()),
                ('p_grasa', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Asist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('id_Cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestorClient.client')),
            ],
        ),
    ]
